sudo: required
language: cpp

services:
  - docker

before_install:
  - docker pull ilssim/main

script:
  - docker run -t -i -v $PWD:/src -w /src ilssim/main /bin/bash -c './build.sh'

after_script:
  - ls -al cpp_out/
  - ls -al csharp_out/
