sudo: required
language: cpp
cache: ccache
before_install:
- ./install_protobuf.sh
install:
#before_script:
script:
- build.sh
#after_success:
#after_failure:
#before_deploy:
#deploy:
#after_deploy:
#after_script:
